# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_USER: $USERNAME_DB
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - $DOCKER_POSTGRES_PORTS_DB
         
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
